apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backups.myorg.io
spec:
  group: myorg.io
  names:
    plural: backups
    singular: backup
    kind: Backup
    shortNames:
      - bk
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                dbName:
                  type: string
                schedule:
                  type: string
  scope: Namespaced
