apiVersion: apps/v1
kind: Deployment
metadata:
  name: climate-app-deployment
  namespace: network
spec:
  replicas: 1
  selector:
    matchLabels:
      app: climate-app
  template:
    metadata:
      labels:
        app: climate-app
    spec:
      containers:
        - name: climate-app
          image: dattarahegaonkar09/climate-app
          ports:
            - containerPort: 5173
          env:
            - name: API_KEY
              value: "d0f143115c3546d095590925242206"
