apiVersion: v1
kind: Service
metadata:
  name: climate-app-service
  namespace: network
spec:
  selector:
    app: climate-app
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: ClusterIP
