apiVersion: v1
kind: Pod
metadata:
  name: init-container
spec:
  initContainers:
  - name: init-container
    image: busybox
    command: ['sh', '-c', 'echo initializing... && sleep 5']
  containers:
  - name: main-container
    image: nginx

